"""empty message

Revision ID: 00f097111be6
Revises: 174eee9a9e78
Create Date: 2019-01-19 02:01:31.439156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f097111be6'
down_revision = '174eee9a9e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hits', 'summary')
    # ### end Alembic commands ###
