"""empty message

Revision ID: 0243b2246dcb
Revises: c7f42cb29c52
Create Date: 2018-12-25 18:15:01.312321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0243b2246dcb'
down_revision = 'c7f42cb29c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('company', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hits', 'company')
    # ### end Alembic commands ###
