"""empty message

Revision ID: 117fbb99773a
Revises: 6a08ab515646
Create Date: 2019-01-12 19:03:02.196736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117fbb99773a'
down_revision = '6a08ab515646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('tagged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hits', 'tagged')
    # ### end Alembic commands ###
