"""empty message

Revision ID: 21ff3c586afc
Revises: 43fa30ddd5ce
Create Date: 2018-12-25 11:46:16.178751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ff3c586afc'
down_revision = '43fa30ddd5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hit_count_by_company')
    op.drop_table('hit_count_by_location')
    op.drop_table('hit_count_by_search_term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit_count_by_search_term',
    sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['term'], ['search_term.id'], name='hit_count_by_search_term_term_fkey'),
    sa.PrimaryKeyConstraint('count', name='hit_count_by_search_term_pkey')
    )
    op.create_table('hit_count_by_location',
    sa.Column('loc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['loc'], ['locations.id'], name='hit_count_by_location_loc_fkey'),
    sa.PrimaryKeyConstraint('count', name='hit_count_by_location_pkey')
    )
    op.create_table('hit_count_by_company',
    sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], name='hit_count_by_company_company_fkey'),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], name='hit_count_by_company_location_fkey'),
    sa.PrimaryKeyConstraint('company', 'location', name='hit_count_by_company_pkey')
    )
    # ### end Alembic commands ###
