"""empty message

Revision ID: 2d4dfcdbaedf
Revises: 9baafd76078d
Create Date: 2019-01-12 22:44:51.760334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4dfcdbaedf'
down_revision = '9baafd76078d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('applied', sa.Boolean(), nullable=True))
    op.add_column('hits', sa.Column('interested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hits', 'interested')
    op.drop_column('hits', 'applied')
    # ### end Alembic commands ###
