"""empty message

Revision ID: 3a283ab36083
Revises: 117fbb99773a
Create Date: 2019-01-12 19:06:22.414499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a283ab36083'
down_revision = '117fbb99773a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('marked_for_deletion', sa.Boolean(), nullable=True))
    op.drop_column('hits', 'tagged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('tagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hits', 'marked_for_deletion')
    # ### end Alembic commands ###
