"""empty message

Revision ID: 43fa30ddd5ce
Revises: 
Create Date: 2018-12-25 11:32:53.776704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fa30ddd5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_created_date'), 'company', ['created_date'], unique=False)
    op.create_index(op.f('ix_company_updated_date'), 'company', ['updated_date'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('full', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_created_date'), 'locations', ['created_date'], unique=False)
    op.create_index(op.f('ix_locations_updated_date'), 'locations', ['updated_date'], unique=False)
    op.create_table('search_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_term_created_date'), 'search_term', ['created_date'], unique=False)
    op.create_index(op.f('ix_search_term_updated_date'), 'search_term', ['updated_date'], unique=False)
    op.create_table('unique_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_copus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hit_count_by_company',
    sa.Column('company', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('company', 'location')
    )
    op.create_table('hit_count_by_location',
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loc'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('hit_count_by_search_term',
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term'], ['search_term.id'], ),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('hits',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.Numeric(), nullable=True),
    sa.Column('max_salary', sa.Numeric(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['loc'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['term'], ['search_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hits_created_date'), 'hits', ['created_date'], unique=False)
    op.create_index(op.f('ix_hits_id'), 'hits', ['id'], unique=False)
    op.create_index(op.f('ix_hits_updated_date'), 'hits', ['updated_date'], unique=False)
    op.create_table('word_copus_count',
    sa.Column('word', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word'], ['unique_words.id'], ),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_copus_count')
    op.drop_index(op.f('ix_hits_updated_date'), table_name='hits')
    op.drop_index(op.f('ix_hits_id'), table_name='hits')
    op.drop_index(op.f('ix_hits_created_date'), table_name='hits')
    op.drop_table('hits')
    op.drop_table('hit_count_by_search_term')
    op.drop_table('hit_count_by_location')
    op.drop_table('hit_count_by_company')
    op.drop_table('word_copus')
    op.drop_table('users')
    op.drop_table('unique_words')
    op.drop_index(op.f('ix_search_term_updated_date'), table_name='search_term')
    op.drop_index(op.f('ix_search_term_created_date'), table_name='search_term')
    op.drop_table('search_term')
    op.drop_index(op.f('ix_locations_updated_date'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_date'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_company_updated_date'), table_name='company')
    op.drop_index(op.f('ix_company_created_date'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
