"""empty message

Revision ID: 4c856b98d472
Revises: f9d2babba45e
Create Date: 2019-01-13 10:50:27.246641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c856b98d472'
down_revision = 'f9d2babba45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('offer', sa.Boolean(), nullable=True))
    op.drop_column('hits', 'offered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('offered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hits', 'offer')
    # ### end Alembic commands ###
