"""empty message

Revision ID: 635b69eb7b9b
Revises: 21ff3c586afc
Create Date: 2018-12-25 18:13:38.714962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b69eb7b9b'
down_revision = '21ff3c586afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hits_company_fkey', 'hits', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('hits_company_fkey', 'hits', 'company', ['company'], ['id'])
    # ### end Alembic commands ###
