"""empty message

Revision ID: 6a08ab515646
Revises: 6c9607655c03
Create Date: 2018-12-25 18:20:26.143604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a08ab515646'
down_revision = '6c9607655c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hits',
    sa.Column('jid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.Numeric(), nullable=True),
    sa.Column('max_salary', sa.Numeric(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['loc'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['term'], ['search_term.id'], ),
    sa.PrimaryKeyConstraint('jid')
    )
    op.create_index(op.f('ix_hits_created_date'), 'hits', ['created_date'], unique=False)
    op.create_index(op.f('ix_hits_id'), 'hits', ['id'], unique=False)
    op.create_index(op.f('ix_hits_updated_date'), 'hits', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hits_updated_date'), table_name='hits')
    op.drop_index(op.f('ix_hits_id'), table_name='hits')
    op.drop_index(op.f('ix_hits_created_date'), table_name='hits')
    op.drop_table('hits')
    # ### end Alembic commands ###
