"""empty message

Revision ID: 6c9607655c03
Revises: 9091dea75f18
Create Date: 2018-12-25 18:17:30.088235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c9607655c03'
down_revision = '9091dea75f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('hits', sa.Column('taco', sa.Integer(), nullable=False))
    op.drop_index('ix_hits_created_date', table_name='hits')
    op.drop_index('ix_hits_updated_date', table_name='hits')
    op.drop_constraint('hits_loc_fkey', 'hits', type_='foreignkey')
    op.drop_constraint('hits_term_fkey', 'hits', type_='foreignkey')
    op.drop_column('hits', 'term')
    op.drop_column('hits', 'salary')
    op.drop_column('hits', 'loc')
    op.drop_column('hits', 'summary')
    op.drop_column('hits', 'min_salary')
    op.drop_column('hits', 'created_date')
    op.drop_column('hits', 'id')
    op.drop_column('hits', 'max_salary')
    op.drop_column('hits', 'title')
    op.drop_column('hits', 'url')
    op.drop_column('hits', 'company')
    op.drop_column('hits', 'updated_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hits', sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('max_salary', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('hits', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('min_salary', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('loc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('salary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hits', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hits_term_fkey', 'hits', 'search_term', ['term'], ['id'])
    op.create_foreign_key('hits_loc_fkey', 'hits', 'locations', ['loc'], ['id'])
    op.create_index('ix_hits_updated_date', 'hits', ['updated_date'], unique=False)
    op.create_index('ix_hits_created_date', 'hits', ['created_date'], unique=False)
    op.drop_column('hits', 'taco')
    # ### end Alembic commands ###
