"""empty message

Revision ID: 9091dea75f18
Revises: 0243b2246dcb
Create Date: 2018-12-25 18:17:04.097151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9091dea75f18'
down_revision = '0243b2246dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hits_id', table_name='hits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_hits_id', 'hits', ['id'], unique=False)
    # ### end Alembic commands ###
