"""empty message

Revision ID: c042a1f6d78f
Revises: d97a08793b7c
Create Date: 2019-01-19 01:33:34.878128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c042a1f6d78f'
down_revision = 'd97a08793b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('num_jobs', sa.Integer(), nullable=True))
    op.add_column('search_term', sa.Column('num_jobs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_term', 'num_jobs')
    op.drop_column('locations', 'num_jobs')
    # ### end Alembic commands ###
