"""empty message

Revision ID: c63392919ce2
Revises: 4c856b98d472
Create Date: 2019-01-19 01:25:19.044990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63392919ce2'
down_revision = '4c856b98d472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('num_jobs', sa.Integer(), nullable=True))
    op.add_column('search_term', sa.Column('num_jobs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_term', 'num_jobs')
    op.drop_column('locations', 'num_jobs')
    # ### end Alembic commands ###
