"""empty message

Revision ID: d97a08793b7c
Revises: c63392919ce2
Create Date: 2019-01-19 01:33:27.669882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97a08793b7c'
down_revision = 'c63392919ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'num_jobs')
    op.drop_column('search_term', 'num_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_term', sa.Column('num_jobs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('num_jobs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
